version: 2

project_name: dibbla

before:
  hooks:
    - go mod tidy

builds:
  - id: dibbla
    main: ./cmd/dibbla
    binary: dibbla
    ldflags:
      - -s -w
      - -X github.com/dibbla-agents/dibbla-cli/internal/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "dibbla_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: dibbla-agents
    name: dibbla-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

