version: 2

project_name: dibbla

before:
  hooks:
    - go mod tidy

builds:
  - id: dibbla
    main: ./cmd/dibbla
    binary: dibbla
    ldflags:
      - -s -w
      - -X github.com/dibbla-agents/dibbla-cli/internal/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "dibbla_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: dibbla-agents
    name: dibbla-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: dibbla
    repository:
      owner: dibbla-agents
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    directory: Formula
    description: "Dibbla CLI for managing Dibbla applications"
    homepage: "https://dibbla.com"

    install: |
      bin.install "dibbla"
      # Generate and install shell completions
      (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
      (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
      (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
    test: |
      system "#{bin}/dibbla --version"

nfpms:
  - id: dibbla-deb
    package_name: dibbla
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
    builds:
      - dibbla

    formats:
      - deb
      - rpm

    vendor: "Dibbla Agents"
    homepage: "https://dibbla.com"
    description: "Dibbla CLI for managing Dibbla applications"

    contents:
      - src: ./dibbla
        dst: /usr/bin/dibbla