package skills

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// sourceDir is the authored skill, from which the embedded copy is generated by
// `go generate ./internal/cmd/skills/...`.
const sourceDir = "../../../.claude/skills/dibbla"

// TestDibblaSkill_ByteSyncedWithSource fails when the authored skill and the
// embedded copy have drifted — which is what happens when someone edits
// .claude/skills/dibbla/*.md and forgets to run `go generate`. Presence tests
// cannot catch that: the file is there, it is simply stale.
func TestDibblaSkill_ByteSyncedWithSource(t *testing.T) {
	sub, err := fs.Sub(dibblaSkillFS, dibblaSkillRoot)
	if err != nil {
		t.Fatalf("fs.Sub(%q): %v", dibblaSkillRoot, err)
	}

	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		t.Fatalf("read %s: %v", sourceDir, err)
	}

	want := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		want[e.Name()] = true

		source, err := os.ReadFile(filepath.Join(sourceDir, e.Name()))
		if err != nil {
			t.Fatalf("read source %s: %v", e.Name(), err)
		}
		embedded, err := fs.ReadFile(sub, e.Name())
		if err != nil {
			t.Errorf("%s is in the authored skill but not embedded — run `go generate ./...`", e.Name())
			continue
		}
		if string(source) != string(embedded) {
			t.Errorf("%s differs between the authored skill (%d bytes) and the embedded copy (%d bytes) — run `go generate ./...`",
				e.Name(), len(source), len(embedded))
		}
	}

	if len(want) == 0 {
		t.Fatalf("no .md files found in %s — the test is not proving anything", sourceDir)
	}

	embeddedNames, err := fs.ReadDir(sub, ".")
	if err != nil {
		t.Fatalf("read embedded dir: %v", err)
	}
	for _, e := range embeddedNames {
		if !want[e.Name()] {
			t.Errorf("%s is embedded but no longer exists in the authored skill — run `go generate ./...`", e.Name())
		}
	}
}

// TestSkill_DocumentsApplicationChecks pins the P-0033 Part H documentation
// contract: the agent-facing skill must carry the dibbla-checks.yaml schema, the
// rules a draft is most often rejected for, and the disambiguation from a
// dibbla.yaml healthcheck. Losing any of these silently is how an agent starts
// inventing fields again.
func TestSkill_DocumentsApplicationChecks(t *testing.T) {
	read := func(name string) string {
		data, err := os.ReadFile(filepath.Join(sourceDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		return string(data)
	}

	manifest := read("manifest.md")
	platform := read("platform.md")
	skill := read("SKILL.md")

	for _, want := range []struct{ file, doc, needle string }{
		{"manifest.md", manifest, "## 22. Application checks (`dibbla-checks.yaml`)"},
		{"manifest.md", manifest, "identity_grant"},
		{"manifest.md", manifest, "APPLICATION_CHECKS_INLINE_SECRET"},
		{"manifest.md", manifest, "reducer: all_required"},
		{"manifest.md", manifest, "### 22.6. Not the same as a § 12 healthcheck"},
		// The healthcheck section must point forward, or a reader who starts at
		// § 12 never learns that application checks exist.
		{"manifest.md", manifest, "This is not \"does my app still work\"."},
		{"platform.md", platform, "## 8.7. Application checks — the runtime model"},
		{"platform.md", platform, "application.check.recovered"},
		{"SKILL.md", skill, "Application checks (`dibbla-checks.yaml`):"},
	} {
		if !strings.Contains(want.doc, want.needle) {
			t.Errorf("%s no longer contains %q", want.file, want.needle)
		}
	}
}

// TestSkill_DocumentsEnvPull pins the DIB-919 documentation contract: an
// agent asked to "set up a local environment" must find the model (values in
// Dibbla, names in the code), the command, the five steps, the .env.example
// exception in the filter list, and the guardrail that a .env.local git
// cannot see is expected rather than a blocker. Losing any of these is how an
// agent goes back to `secrets get` one value at a time — or flags the file
// env pull just wrote.
func TestSkill_DocumentsEnvPull(t *testing.T) {
	read := func(name string) string {
		data, err := os.ReadFile(filepath.Join(sourceDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		return string(data)
	}
	skill, reference, examples, guardrails, platform := read("SKILL.md"), read("reference.md"), read("examples.md"), read("guardrails.md"), read("platform.md")
	for _, want := range []struct{ file, doc, needle string }{
		{"SKILL.md", skill, "Secrets and the local environment — values live in Dibbla, names live in the code"},
		{"SKILL.md", skill, "`dibbla env pull`"},
		{"SKILL.md", skill, "same database as the real app"},
		{"SKILL.md", skill, "offer a local Postgres"},
		{"reference.md", reference, "### env pull"},
		{"reference.md", reference, "`.env.example` and `.env.sample` (exact names) are kept"},
		{"examples.md", examples, "### Set up a local development environment (env pull)"},
		// DIB-1343: the new-secret step is a request the person answers in
		// the browser; DIB-1340: a secret-looking variable is promoted.
		{"examples.md", examples, "dibbla secrets request STRIPE_API_KEY"},
		{"examples.md", examples, "dibbla env promote STRIPE_SECRET_KEY"},
		{"guardrails.md", guardrails, "A `.env.local` that *is* in `.gitignore` is expected"},
		{"platform.md", platform, "**Except `.env.example` and `.env.sample`**"},
		// DIB-1338/DIB-1345: secrets are write-only, so the reveal row names
		// the caller's own credentials only — `db connect` and `storage
		// credentials` — and env pull is its own row, which reveals no
		// secret value.
		{"platform.md", platform, "| `cli.credentials.reveal` | `db connect`, `storage credentials` |"},
		{"platform.md", platform, "| `cli.env.pull` | `env pull` |"},
		{"platform.md", platform, "`env pull` reveals no secret value"},
	} {
		if !strings.Contains(want.doc, want.needle) {
			t.Errorf("%s no longer contains %q", want.file, want.needle)
		}
	}
	// The old guardrail row called the file env pull writes a BLOCKER.
	if strings.Contains(guardrails, "| `.env` files present in the deploy directory | BLOCKER |") {
		t.Error("guardrails.md still calls every .env file in the folder a BLOCKER")
	}
}

// TestSkill_LocalRunTakesDatabaseURLFromDBConnect pins where a local run gets
// its database URL. `env pull` writes DATABASE_URL_* by name only — it is a
// secret, write-only since DIB-1337 — and `dibbla db connect` is the way to a
// connection of your own. That URL carries the person's API token, so the
// skill sends it into the start command rather than into .env.local.
func TestSkill_LocalRunTakesDatabaseURLFromDBConnect(t *testing.T) {
	read := func(path string) string {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		return string(data)
	}
	skill := read(filepath.Join(sourceDir, "SKILL.md"))
	reference := read(filepath.Join(sourceDir, "reference.md"))
	examples := read(filepath.Join(sourceDir, "examples.md"))
	platform := read(filepath.Join(sourceDir, "platform.md"))
	rootSkill := read("../../../SKILL.md")
	for _, want := range []struct{ file, doc, needle string }{
		{"SKILL.md", skill, "set in the start command from `dibbla db connect <name> -q`"},
		{"reference.md", reference, "| **Database from your machine** |"},
		{"examples.md", examples, "-e DATABASE_URL_MY_APP_DB=\"$(dibbla db connect my_app_db -q)\""},
		{"platform.md", platform, "from your own machine, connect with `dibbla db connect <name> -q`"},
		{"root SKILL.md", rootSkill, "**Database from your machine:**"},
	} {
		if !strings.Contains(want.doc, want.needle) {
			t.Errorf("%s no longer contains %q", want.file, want.needle)
		}
	}
	for _, stale := range []struct{ file, doc, needle string }{
		{"reference.md", reference, "reach the real database and buckets through the public proxy"},
		{"examples.md", examples, "which `env pull` keeps on the next run"},
		{"root SKILL.md", rootSkill, "are in the set and reach the real database and buckets"},
	} {
		if strings.Contains(stale.doc, stale.needle) {
			t.Errorf("%s still says %q — a pulled DATABASE_URL_* can be cluster-internal", stale.file, stale.needle)
		}
	}
}
