package skills

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// sourceDir is the authored skill, from which the embedded copy is generated by
// `go generate ./internal/cmd/skills/...`.
const sourceDir = "../../../.claude/skills/dibbla"

// TestDibblaSkill_ByteSyncedWithSource fails when the authored skill and the
// embedded copy have drifted — which is what happens when someone edits
// .claude/skills/dibbla/*.md and forgets to run `go generate`. Presence tests
// cannot catch that: the file is there, it is simply stale.
func TestDibblaSkill_ByteSyncedWithSource(t *testing.T) {
	sub, err := fs.Sub(dibblaSkillFS, dibblaSkillRoot)
	if err != nil {
		t.Fatalf("fs.Sub(%q): %v", dibblaSkillRoot, err)
	}

	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		t.Fatalf("read %s: %v", sourceDir, err)
	}

	want := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		want[e.Name()] = true

		source, err := os.ReadFile(filepath.Join(sourceDir, e.Name()))
		if err != nil {
			t.Fatalf("read source %s: %v", e.Name(), err)
		}
		embedded, err := fs.ReadFile(sub, e.Name())
		if err != nil {
			t.Errorf("%s is in the authored skill but not embedded — run `go generate ./...`", e.Name())
			continue
		}
		if string(source) != string(embedded) {
			t.Errorf("%s differs between the authored skill (%d bytes) and the embedded copy (%d bytes) — run `go generate ./...`",
				e.Name(), len(source), len(embedded))
		}
	}

	if len(want) == 0 {
		t.Fatalf("no .md files found in %s — the test is not proving anything", sourceDir)
	}

	embeddedNames, err := fs.ReadDir(sub, ".")
	if err != nil {
		t.Fatalf("read embedded dir: %v", err)
	}
	for _, e := range embeddedNames {
		if !want[e.Name()] {
			t.Errorf("%s is embedded but no longer exists in the authored skill — run `go generate ./...`", e.Name())
		}
	}
}

// TestSkill_DocumentsApplicationChecks pins the P-0033 Part H documentation
// contract: the agent-facing skill must carry the dibbla-checks.yaml schema, the
// rules a draft is most often rejected for, and the disambiguation from a
// dibbla.yaml healthcheck. Losing any of these silently is how an agent starts
// inventing fields again.
func TestSkill_DocumentsApplicationChecks(t *testing.T) {
	read := func(name string) string {
		data, err := os.ReadFile(filepath.Join(sourceDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		return string(data)
	}

	manifest := read("manifest.md")
	platform := read("platform.md")
	skill := read("SKILL.md")

	for _, want := range []struct{ file, doc, needle string }{
		{"manifest.md", manifest, "## 22. Application checks (`dibbla-checks.yaml`)"},
		{"manifest.md", manifest, "identity_grant"},
		{"manifest.md", manifest, "APPLICATION_CHECKS_INLINE_SECRET"},
		{"manifest.md", manifest, "reducer: all_required"},
		{"manifest.md", manifest, "### 22.6. Not the same as a § 12 healthcheck"},
		// The healthcheck section must point forward, or a reader who starts at
		// § 12 never learns that application checks exist.
		{"manifest.md", manifest, "This is not \"does my app still work\"."},
		{"platform.md", platform, "## 8.7. Application checks — the runtime model"},
		{"platform.md", platform, "application.check.recovered"},
		{"SKILL.md", skill, "Application checks (`dibbla-checks.yaml`):"},
	} {
		if !strings.Contains(want.doc, want.needle) {
			t.Errorf("%s no longer contains %q", want.file, want.needle)
		}
	}
}
