package export

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dibbla-agents/dibbla-cli/internal/manifest"
	"github.com/dibbla-agents/dibbla-cli/internal/storage"
)

// composeService is one app service as the compose sketch renders it.
type composeService struct {
	Name         string
	BuildContext string // relative to the export root; "" when Image is set
	Dockerfile   string
	Image        string
	Port         *int
	Public       bool
	Command      []string
	Entrypoint   []string
}

// composeServices derives the services to render: from the app's own
// dibbla.yaml when the export carries one it can parse, else from the
// deployed configuration. Sorted by name so the output is stable.
func composeServices(m *Manifest, sourceManifest *manifest.Manifest) []composeService {
	var out []composeService
	switch {
	case sourceManifest != nil:
		for name, s := range sourceManifest.Services {
			cs := composeService{Name: name, Port: s.Port, Command: s.Command, Entrypoint: s.Entrypoint}
			cs.Public = publicFlag(s.Public)
			switch b := s.Build.(type) {
			case string:
				cs.BuildContext = sourcePath(b)
			case map[string]any:
				ctx, _ := b["context"].(string)
				cs.BuildContext = sourcePath(ctx)
				cs.Dockerfile, _ = b["dockerfile"].(string)
			case nil:
				if ref, ok := s.Image.(string); ok {
					cs.Image = ref
				} else {
					// Env-aware image map: the server resolved it; use that.
					cs.Image = deployedImage(m, name)
				}
			}
			out = append(out, cs)
		}
	case len(m.App.Services) > 0:
		for _, s := range m.App.Services {
			cs := composeService{Name: s.Name, Port: s.Port, Public: s.IsPublic || m.singlePublicService()}
			if s.IsBuilt || s.Image == "" {
				cs.BuildContext = "./source"
			} else {
				cs.Image = s.Image
			}
			out = append(out, cs)
		}
	default:
		out = append(out, composeService{Name: m.App.Alias, BuildContext: "./source", Port: m.App.Port, Public: true})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func publicFlag(v any) bool {
	switch p := v.(type) {
	case bool:
		return p
	case map[string]any:
		for _, x := range p {
			if b, ok := x.(bool); ok && b {
				return true
			}
		}
	}
	return false
}

func deployedImage(m *Manifest, service string) string {
	for _, s := range m.App.Services {
		if s.Name == service {
			return s.Image
		}
	}
	return ""
}

// sourcePath maps a manifest build path (relative to the app root) to a
// compose context relative to the export root.
func sourcePath(p string) string {
	p = strings.TrimSpace(p)
	if p == "" || p == "." || p == "./" {
		return "./source"
	}
	return "./source/" + strings.TrimPrefix(filepath.ToSlash(filepath.Clean(p)), "./")
}

// loadSourceManifest parses source/dibbla.yaml when the export copied it;
// an unparsable one is not fatal — the compose file then follows the
// deployed configuration instead.
func loadSourceManifest(outDir string, m *Manifest) *manifest.Manifest {
	if m.ManifestOrigin != "source" {
		return nil
	}
	data, err := os.ReadFile(filepath.Join(outDir, "dibbla.yaml"))
	if err != nil {
		return nil
	}
	parsed, err := manifest.ParseAndValidateBytes(data)
	if err != nil {
		m.Warnings = append(m.Warnings, "dibbla.yaml could not be parsed for the compose sketch: "+err.Error())
		return nil
	}
	return parsed
}

// dbURLVar is the name of the DATABASE_URL_<DB> variable the platform
// injects for a database, mirroring the server transform.
func dbURLVar(dbName string) string { return "DATABASE_URL_" + strings.ToUpper(dbName) }

// composeFile renders the docker compose sketch: every app service built
// from the exported source, a Postgres seeded from the dumps and a MinIO
// seeded from the bucket directories, wired together through the same
// variable names the app read on Dibbla.
func composeFile(m *Manifest, env envFileSet, services []composeService) string {
	var b strings.Builder
	b.WriteString("# docker compose sketch generated by dibbla export for app " + m.App.Alias + ".\n")
	b.WriteString("# It is a starting point, not a product: adjust images, ports and resources to taste.\n")
	b.WriteString("#   docker compose up --build\n")
	b.WriteString("# Databases are restored from ./databases on first start (empty pgdata volume);\n")
	b.WriteString("# buckets are mirrored from ./buckets into MinIO on every start.\n")
	b.WriteString("services:\n")

	hostPort := 8080
	for _, s := range services {
		b.WriteString("  " + s.Name + ":\n")
		if s.Image != "" {
			fmt.Fprintf(&b, "    image: %s\n", yamlString(s.Image))
		} else {
			b.WriteString("    build:\n")
			fmt.Fprintf(&b, "      context: %s\n", s.BuildContext)
			if s.Dockerfile != "" {
				fmt.Fprintf(&b, "      dockerfile: %s\n", s.Dockerfile)
			}
		}
		if len(s.Entrypoint) > 0 {
			fmt.Fprintf(&b, "    entrypoint: %s\n", yamlList(s.Entrypoint))
		}
		if len(s.Command) > 0 {
			fmt.Fprintf(&b, "    command: %s\n", yamlList(s.Command))
		}
		b.WriteString("    env_file:\n")
		fmt.Fprintf(&b, "      - %s\n", env.App)
		if f, ok := env.Services[s.Name]; ok {
			fmt.Fprintf(&b, "      - %s\n", f)
		}
		b.WriteString("    environment:\n")
		for _, d := range m.Databases {
			fmt.Fprintf(&b, "      %s: postgres://postgres:postgres@postgres:5432/%s?sslmode=disable\n", dbURLVar(d.Name), d.Name)
		}
		for _, bk := range m.Buckets {
			n := storage.EnvName(bk.Name)
			fmt.Fprintf(&b, "      STORAGE_%s_ENDPOINT: http://minio:9000\n", n)
			fmt.Fprintf(&b, "      STORAGE_%s_BUCKET: %s\n", n, bk.Name)
			fmt.Fprintf(&b, "      STORAGE_%s_ACCESS_KEY_ID: minioadmin\n", n)
			fmt.Fprintf(&b, "      STORAGE_%s_SECRET_ACCESS_KEY: minioadmin\n", n)
		}
		for _, other := range services {
			if other.Name == s.Name || other.Port == nil {
				continue
			}
			n := storage.EnvName(other.Name)
			fmt.Fprintf(&b, "      DIBBLA_SVC_%s_HOST: %s\n", n, other.Name)
			fmt.Fprintf(&b, "      DIBBLA_SVC_%s_PORT: \"%d\"\n", n, *other.Port)
			fmt.Fprintf(&b, "      DIBBLA_SVC_%s_URL: http://%s:%d\n", n, other.Name, *other.Port)
		}
		if s.Public && s.Port != nil {
			b.WriteString("    ports:\n")
			fmt.Fprintf(&b, "      - \"%d:%d\"\n", hostPort, *s.Port)
			hostPort++
		}
		if len(m.Databases) > 0 || len(m.Buckets) > 0 {
			b.WriteString("    depends_on:\n")
			if len(m.Databases) > 0 {
				b.WriteString("      postgres:\n        condition: service_healthy\n")
			}
			if len(m.Buckets) > 0 {
				b.WriteString("      minio-seed:\n        condition: service_completed_successfully\n")
			}
		}
	}

	if len(m.Databases) > 0 {
		b.WriteString(`  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./databases:/dumps:ro
      - ./compose/restore-databases.sh:/docker-entrypoint-initdb.d/10-restore-databases.sh:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
`)
	}
	if len(m.Buckets) > 0 {
		b.WriteString(`  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 20
  minio-seed:
    image: quay.io/minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./buckets:/seed:ro
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mc alias set local http://minio:9000 minioadmin minioadmin
`)
		for _, bk := range m.Buckets {
			fmt.Fprintf(&b, "        mc mb --ignore-existing local/%s\n", bk.Name)
			fmt.Fprintf(&b, "        mc mirror --overwrite /seed/%s local/%s\n", bk.Name, bk.Name)
		}
	}
	if len(m.Databases) > 0 || len(m.Buckets) > 0 {
		b.WriteString("volumes:\n")
		if len(m.Databases) > 0 {
			b.WriteString("  pgdata:\n")
		}
		if len(m.Buckets) > 0 {
			b.WriteString("  miniodata:\n")
		}
	}
	return b.String()
}

// restoreScript is mounted into the Postgres image's init directory: it
// creates each database and restores its custom-format dump. Ownership and
// grants are dropped on purpose — the roles they name are Dibbla's.
func restoreScript(m *Manifest) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# Generated by dibbla export. Runs once, on the first start of an empty pgdata volume.\nset -eu\n")
	for _, d := range m.Databases {
		fmt.Fprintf(&b, "echo \"restoring %s from /dumps/%s.dump\"\n", d.Name, d.Name)
		fmt.Fprintf(&b, "createdb -U postgres %q\n", d.Name)
		fmt.Fprintf(&b, "pg_restore -U postgres --no-owner --no-privileges -d %q /dumps/%s.dump\n", d.Name, d.Name)
	}
	return b.String()
}

// yamlString quotes a scalar only when YAML could read it as something
// else — image references with ":tag" stay plain, like people write them.
func yamlString(s string) string {
	if s == "" || strings.ContainsAny(s, "\n\"'") || strings.Contains(s, ": ") || strings.Contains(s, " #") ||
		strings.ContainsAny(string(s[0]), "-?:,[]{}#&*!|>%@`") {
		return fmt.Sprintf("%q", s)
	}
	return s
}

func yamlList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// readme is the human entry point of the export: what is in it and how to
// bring it up somewhere else.
func readme(m *Manifest, includeSecrets bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Export of %s from Dibbla\n\n", m.App.Alias)
	fmt.Fprintf(&b, "Exported %s", m.ExportedAt.Format("2006-01-02 15:04 UTC"))
	if m.CLIVersion != "" {
		fmt.Fprintf(&b, " with dibbla CLI %s", m.CLIVersion)
	}
	b.WriteString(". Everything the app kept on Dibbla, in formats other tools read.\n\n")

	b.WriteString("## What is here\n\n")
	b.WriteString("| Path | What | Format |\n|---|---|---|\n")
	if m.Source != nil {
		fmt.Fprintf(&b, "| `source/` | the app's source, every deploy as a commit (latest `%s`) | git repository |\n", short(m.Source.Commit))
	} else {
		fmt.Fprintf(&b, "| `source/` | not exported: %s | — |\n", m.SourceUnavailable)
	}
	fmt.Fprintf(&b, "| `dibbla.yaml` | the app's manifest (%s) | dibbla.yaml |\n", m.ManifestOrigin)
	for _, d := range m.Databases {
		fmt.Fprintf(&b, "| `%s` | database `%s` (%s) | pg_dump custom archive — `pg_restore` |\n", d.File, d.Name, storage.FormatBytes(d.SizeBytes))
	}
	for _, bk := range m.Buckets {
		fmt.Fprintf(&b, "| `%s/` | bucket `%s`, %d object(s) (%s), one file per object key | plain files |\n", bk.Path, bk.Name, bk.Objects, storage.FormatBytes(bk.Bytes))
	}
	for _, f := range m.Env.Files {
		fmt.Fprintf(&b, "| `%s` | environment variables | dotenv |\n", f)
	}
	b.WriteString("| `docker-compose.yml` | runs the above together locally | docker compose |\n")
	b.WriteString("| `dibbla-export.json` | machine-readable inventory of this export | JSON |\n\n")

	b.WriteString("## Secrets\n\n")
	if includeSecrets {
		b.WriteString("Secret values **are included** in the `env/` files (you asked for `--include-secrets`). Treat this directory as you would a password file.\n\n")
	} else {
		b.WriteString("Secret values are **not** included: the `env/` files list every variable name the app reads, with blanks where a secret was. Fill them in, or re-run `dibbla export --include-secrets` to export the values.\n\n")
	}

	b.WriteString("## Run it locally\n\n")
	b.WriteString("Requires Docker with the compose plugin.\n\n```\ndocker compose up --build\n```\n\n")
	if len(m.Databases) > 0 {
		b.WriteString("- Postgres starts on `localhost:5432` (user/password `postgres`) and restores every dump in `databases/` the first time the `pgdata` volume is created. `DATABASE_URL_*` is pointed at it with `sslmode=disable`.\n")
	}
	if len(m.Buckets) > 0 {
		b.WriteString("- MinIO starts on `localhost:9000` (console `localhost:9001`, `minioadmin`/`minioadmin`); `minio-seed` mirrors `buckets/` into it. `STORAGE_*` is pointed at it.\n")
	}
	b.WriteString("- Public services are published from `localhost:8080` upwards, in name order.\n")
	b.WriteString("- Things Dibbla did in front of the app and that are not here: login and the `X-User-*` headers, custom domains and TLS, `${DIBBLA_SVC_*}` are set to plain compose DNS names, and no scheduled jobs run.\n\n")

	b.WriteString("## Take it somewhere else\n\n")
	b.WriteString("- **Source:** `source/` is a normal git repository — add a remote and push.\n")
	if len(m.Databases) > 0 {
		b.WriteString("- **Databases:** `pg_restore --no-owner --no-privileges -d <db> databases/<name>.dump` into any PostgreSQL 15+.\n")
	}
	if len(m.Buckets) > 0 {
		b.WriteString("- **Buckets:** copy `buckets/<name>/` to any S3-compatible store (`aws s3 sync`, `mc mirror`, `rclone`); the directory layout is the object keys.\n")
	}
	b.WriteString("- **Configuration:** `dibbla.yaml` names the services, ports and inline environment; `env/` names the rest.\n")
	if len(m.Warnings) > 0 {
		b.WriteString("\n## Notes from the export\n\n")
		for _, w := range m.Warnings {
			b.WriteString("- " + w + "\n")
		}
	}
	return b.String()
}

func short(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}
